// <auto-generated />
namespace CoreFirst.Migrations.NHL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class errorhai : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(errorhai));
        
        string IMigrationMetadata.Id
        {
            get { return "201803190931135_errorhai"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
